package com.tb.entity;
// Generated Jan 10, 2020 9:34:01 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AgeRating generated by hbm2java
 */
@Entity
@Table(name = "age_rating",
         catalog = "db_tboopl_20191"
)
public class AgeRating implements java.io.Serializable {

    @Override
    public String toString() {
        return name;
    }

    private Integer id;
    private String name;
    private Set<Film> films = new HashSet<Film>(0);

    public AgeRating() {
    }

    public AgeRating(String name) {
        this.name = name;
    }

    public AgeRating(String name, Set<Film> films) {
        this.name = name;
        this.films = films;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 4)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ageRating")
    public Set<Film> getFilms() {
        return this.films;
    }

    public void setFilms(Set<Film> films) {
        this.films = films;
    }

}
