package com.tb.entity;
// Generated Jan 10, 2020 9:34:01 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Screening generated by hbm2java
 */
@Entity
@Table(name = "screening",
         catalog = "db_tboopl_20191"
)
public class Screening implements java.io.Serializable {

    private Integer id;
    private Film film;
    private Studio studio;
    private Date startAt;
    private Date endAt;
    private double price;
    private Set<Ticket> tickets = new HashSet<Ticket>(0);

    public Screening() {
    }

    public Screening(Film film, Studio studio, Date startAt, double price) {
        this.film = film;
        this.studio = studio;
        this.startAt = startAt;
        this.price = price;
    }

    public Screening(Film film, Studio studio, Date startAt, Date endAt, double price, Set<Ticket> tickets) {
        this.film = film;
        this.studio = studio;
        this.startAt = startAt;
        this.endAt = endAt;
        this.price = price;
        this.tickets = tickets;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "film_id", nullable = false)
    public Film getFilm() {
        return this.film;
    }

    public void setFilm(Film film) {
        this.film = film;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "studio_id", nullable = false)
    public Studio getStudio() {
        return this.studio;
    }

    public void setStudio(Studio studio) {
        this.studio = studio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start_at", nullable = false, length = 19)
    public Date getStartAt() {
        return this.startAt;
    }

    public void setStartAt(Date startAt) {
        this.startAt = startAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "end_at", length = 19)
    public Date getEndAt() {
        return this.endAt;
    }

    public void setEndAt(Date endAt) {
        this.endAt = endAt;
    }

    @Column(name = "price", nullable = false, precision = 22, scale = 0)
    public double getPrice() {
        return this.price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "screening")
    public Set<Ticket> getTickets() {
        return this.tickets;
    }

    public void setTickets(Set<Ticket> tickets) {
        this.tickets = tickets;
    }

}
