package com.tb.entity;
// Generated Jan 10, 2020 9:34:01 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Studio generated by hbm2java
 */
@Entity
@Table(name = "studio",
         catalog = "db_tboopl_20191"
)
public class Studio implements java.io.Serializable {

    @Override
    public String toString() {
        return "Studio " + id;
    }

    private Integer id;
    private int capacity;
    private Set<Screening> screenings = new HashSet<Screening>(0);

    public Studio() {
    }

    public Studio(int capacity) {
        this.capacity = capacity;
    }

    public Studio(int capacity, Set<Screening> screenings) {
        this.capacity = capacity;
        this.screenings = screenings;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "capacity", nullable = false)
    public int getCapacity() {
        return this.capacity;
    }

    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "studio")
    public Set<Screening> getScreenings() {
        return this.screenings;
    }

    public void setScreenings(Set<Screening> screenings) {
        this.screenings = screenings;
    }

}
