package com.tb.entity;
// Generated Jan 10, 2020 9:34:01 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name="ticket"
    ,catalog="db_tboopl_20191"
)
public class Ticket  implements java.io.Serializable {


     private Integer id;
     private Screening screening;
     private User user;
     private Date purchasedAt;
     private Short rating;

    public Ticket() {
    }

	
    public Ticket(Screening screening, User user, Date purchasedAt) {
        this.screening = screening;
        this.user = user;
        this.purchasedAt = purchasedAt;
    }
    public Ticket(Screening screening, User user, Date purchasedAt, Short rating) {
       this.screening = screening;
       this.user = user;
       this.purchasedAt = purchasedAt;
       this.rating = rating;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="screening_id", nullable=false)
    public Screening getScreening() {
        return this.screening;
    }
    
    public void setScreening(Screening screening) {
        this.screening = screening;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="purchased_at", nullable=false, length=19)
    public Date getPurchasedAt() {
        return this.purchasedAt;
    }
    
    public void setPurchasedAt(Date purchasedAt) {
        this.purchasedAt = purchasedAt;
    }

    
    @Column(name="rating")
    public Short getRating() {
        return this.rating;
    }
    
    public void setRating(Short rating) {
        this.rating = rating;
    }




}


