package com.tb.entity;
// Generated Jan 10, 2020 9:34:01 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="db_tboopl_20191"
    , uniqueConstraints = @UniqueConstraint(columnNames="username") 
)
public class User  implements java.io.Serializable {


     private Integer id;
     private Role role;
     private String username;
     private String password;
     private String name;
     private Set<Ticket> tickets = new HashSet<Ticket>(0);
     private Set<BalanceHistory> balanceHistories = new HashSet<BalanceHistory>(0);

    public User() {
    }

	
    public User(Role role, String username, String password, String name) {
        this.role = role;
        this.username = username;
        this.password = password;
        this.name = name;
    }
    public User(Role role, String username, String password, String name, Set<Ticket> tickets, Set<BalanceHistory> balanceHistories) {
       this.role = role;
       this.username = username;
       this.password = password;
       this.name = name;
       this.tickets = tickets;
       this.balanceHistories = balanceHistories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_id", nullable=false)
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }

    
    @Column(name="username", unique=true, nullable=false, length=12)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="name", nullable=false, length=40)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Ticket> getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set<Ticket> tickets) {
        this.tickets = tickets;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<BalanceHistory> getBalanceHistories() {
        return this.balanceHistories;
    }
    
    public void setBalanceHistories(Set<BalanceHistory> balanceHistories) {
        this.balanceHistories = balanceHistories;
    }




}


